version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats_server
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - DB_HOST=stats-db
      - DB_PORT=5432
      #spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      #SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_server
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: ewm-service
    image: ewm_image
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DB_NAME=ewm_main
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - DB_HOST=ewm-db
      - DB_PORT=5432
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      #spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm